name: Upload release artifacts

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tinygo-org/tinygo:0.31.2
      options: --user root
    steps:

    - name: Prepare
      run: |
        apt-get update
        apt-get install -y make

    - name: Work around CVE-2022-24765
      # We're not on a multi-user machine, so this is safe.
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Dependencies
      run: |
        go mod tidy

    - name: Build XIAO BLE binary
      run: make TARGET=xiao-ble build

    - name: Upload XIAO BLE binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        tag: ${{ github.ref }}
        file: ./build/fpvc-gadget_xiao-ble_*.uf2
        file_glob: true
        asset_name: "fpvc-gadget_xiao-ble_$tag.uf2"
        repo_token: ${{ github.token }}
